<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { IconCloudUpload, IconDatabase, IconFileSearch, IconRefresh, IconSearch } from '@tabler/icons-vue'
import AppShell from '@/components/layout/AppShell.vue'
import { api } from '@/api/services'
import type { KnowledgeBase } from '@/api/contracts'

const bases=ref<KnowledgeBase[]>([]);const keyword=ref('');const selected=ref<KnowledgeBase|null>(null);const uploading=ref(false)
onMounted(async()=>{bases.value=await api.knowledgeBases();selected.value=bases.value[0]})
const filtered=computed(()=>bases.value.filter(x=>`${x.name}${x.description}`.includes(keyword.value)))
const upload=()=>{uploading.value=true;setTimeout(()=>uploading.value=false,1100)}
</script>
<template>
  <AppShell title="知识库管理" subtitle="管理 RAGFlow Dataset、文档解析、切片策略与元数据">
    <div class="kb-toolbar"><label><IconSearch :size="16"/><input v-model="keyword" placeholder="搜索知识库"/></label><button class="secondary-button"><IconRefresh :size="15"/>同步RAGFlow</button><button class="primary-button"><IconDatabase :size="16"/>新建知识库</button></div>
    <div class="kb-layout">
      <section class="kb-list"><button v-for="base in filtered" :key="base.id" :class="['kb-card tech-panel',{active:selected?.id===base.id}]" @click="selected=base"><span class="db-icon"><IconDatabase :size="22"/></span><span><b>{{base.name}}</b><small>{{base.description}}</small><em>{{base.documentCount}} 份文档 · {{base.chunkCount}} 个切片</em></span><i :class="base.status.toLowerCase()">{{base.status}}</i></button></section>
      <section v-if="selected" class="kb-detail tech-panel"><div class="panel-title"><span>{{selected.name}}</span><span class="tag"><i class="status-dot"/>RAGFlow 已同步</span></div><div class="summary"><div><span>文档数</span><b>{{selected.documentCount}}</b></div><div><span>切片数</span><b>{{selected.chunkCount}}</b></div><div><span>向量模型</span><b>{{selected.embeddingModel}}</b></div><div><span>切片策略</span><b>{{selected.chunkMethod}}</b></div></div><div class="meta"><h3>推荐元数据</h3><span v-for="item in ['knowledge_type','industry','product','product_version','gis_domain','region','status','confidentiality','effective_date']" :key="item" class="tag">{{item}}</span></div><div class="documents"><div class="panel-title"><span>最近文档</span><button class="ghost-button"><IconFileSearch :size="15"/>解析状态</button></div><div v-for="(name,i) in ['自然资源一张图建设解决方案V2.pdf','GIS平台总体架构设计规范V2.1.pdf','某省自然资源项目案例.docx','产品部署与配置手册.pdf']" :key="name" class="doc-row"><span><b>{{name}}</b><small>{{['行业=自然资源','产品=GIS平台','状态=已验收','版本=V2.1'][i]}}</small></span><span class="score">已解析</span><em>{{120+i*48}} 个切片</em></div></div><div class="upload-zone" @click="upload"><IconCloudUpload :size="30"/><b>{{uploading?'正在上传并创建解析任务...':'上传资料到当前知识库'}}</b><span>支持 PDF、Word、PPT、Excel、Markdown；上传后由 RAGFlow 解析</span></div></section>
    </div>
  </AppShell>
</template>
<style scoped>
.kb-toolbar{display:flex;gap:8px;justify-content:flex-end;margin-bottom:12px}.kb-toolbar>label{margin-right:auto;width:300px;height:39px;display:flex;align-items:center;gap:8px;padding:0 11px;border:1px solid var(--line);border-radius:6px;color:var(--text-3);background:rgba(3,13,22,.7)}.kb-toolbar input{flex:1;background:none;border:0;outline:0;color:var(--text-1)}.kb-layout{display:grid;grid-template-columns:360px minmax(0,1fr);gap:10px;min-height:calc(100vh - 142px)}.kb-list{display:flex;flex-direction:column;gap:8px;overflow:auto}.kb-card{min-height:92px;padding:12px;display:grid;grid-template-columns:40px 1fr auto;align-items:center;gap:10px;color:var(--text-2);text-align:left}.kb-card:hover,.kb-card.active{border-color:var(--line-strong);background:linear-gradient(135deg,rgba(13,50,74,.94),rgba(4,17,27,.94))}.db-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:6px;background:rgba(25,134,255,.13);color:var(--primary-2)}.kb-card>span:nth-child(2){display:grid;gap:5px}.kb-card b{color:var(--text-1);font-size:12px}.kb-card small,.kb-card em{font-size:10px;color:var(--text-3);font-style:normal}.kb-card>i{font-style:normal;font-size:9px}.kb-card>i.ready{color:var(--success)}.kb-detail{padding:15px;display:flex;flex-direction:column;gap:15px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.summary>div{padding:12px;border:1px solid var(--line);background:rgba(11,39,58,.2);display:grid;gap:7px}.summary span{color:var(--text-3);font-size:10px}.summary b{font-size:15px}.meta{padding-bottom:12px;border-bottom:1px solid var(--line)}.meta h3{font-size:12px}.meta .tag{margin:0 5px 5px 0}.documents{flex:1}.doc-row{min-height:54px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:1fr 70px 90px;align-items:center;gap:10px}.doc-row>span:first-child{display:grid;gap:4px}.doc-row small,.doc-row em{color:var(--text-3);font-size:10px;font-style:normal}.upload-zone{min-height:90px;border:1px dashed var(--line-strong);border-radius:7px;display:grid;place-items:center;align-content:center;gap:6px;color:var(--primary-2);background:rgba(25,134,255,.045)}.upload-zone span{font-size:10px;color:var(--text-3)}@media(max-width:1000px){.kb-layout{grid-template-columns:1fr}.summary{grid-template-columns:repeat(2,1fr)}}
</style>
